package org.firstinspires.ftc.teamcode.common;
public enum Modes {
    AUTO_START,
    TELEOP_START,
    CRUISING,
    LOOKING_FOR_BRICK,
    HOLDING_BRICK,
    HANDING_OFF,
    INTAKING_BRICK_FROM_FLOOR,
    INTAKING_SPECIMEN_FROM_WALL,
    PLACING_BRICK_ON_FLOOR,
    SCORING_SAMPLE,
    SCORING_SPECIMEN,
    PARKING_AT_SUB,
    PARKING_IN_HP_AREA,
    CLIMBING,
    NO_CHANGE;
}

